name: Build

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Validate and format JSON
        run: node src/normalize.mjs

      - name: Run node script to update categories
        run: node src/categories.mjs

      - name: Run node script to update regions
        run: node src/regions.mjs

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          base: HEAD
          filters: |
            categories:
              - 'gitbook/categories/**'
            tools:
              - 'gitbook/tools/**'

      - name: Commit categories
        if: steps.changes.outputs.categories == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gitbook/categories
          git commit -m "Build: Update Categories"

      - name: Commit tools
        if: steps.changes.outputs.tools == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gitbook/tools
          git commit -m "Build: Update Tools"

      - name: Push changes
        if: steps.changes.outputs.categories == 'true' || steps.changes.outputs.tools == 'true'
        uses: ad-m/github-push-action@master
        with:
          branch: main
          force: false
