name: Mark tool updates

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Validate and format JSON
        run: node src/lint-json.mjs

      - name: Mark tool updates
        run: node src/mark-tool-updates.mjs

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          base: HEAD
          filters: |
            all:
              - '**'
            tools:
              - 'gitbook/tools/**'

      - name: Commit tools
        if: steps.changes.outputs.tools == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gitbook/tools
          git commit -m "Mark tool updates"

      - name: Push changes
        if: steps.changes.outputs.all == 'true'
        uses: ad-m/github-push-action@master
        with:
          branch: main

